// diagnose-email.js - Diagnose email connection issues
const nodemailer = require('nodemailer');
const config = require('./config');

async function testMultipleConfigurations() {
    console.log('🔧 Diagnosing Email Connection Issues');
    console.log('=====================================\n');

    const configurations = [
        {
            name: 'SSL/TLS Port 465',
            config: {
                host: config.email.host,
                port: 465,
                secure: true,
                auth: {
                    user: config.email.user,
                    pass: config.email.password
                },
                tls: {
                    rejectUnauthorized: false
                }
            }
        },
        {
            name: 'STARTTLS Port 587',
            config: {
                host: config.email.host,
                port: 587,
                secure: false,
                auth: {
                    user: config.email.user,
                    pass: config.email.password
                },
                tls: {
                    rejectUnauthorized: false
                }
            }
        },
        {
            name: 'Non-secure Port 25',
            config: {
                host: config.email.host,
                port: 25,
                secure: false,
                auth: {
                    user: config.email.user,
                    pass: config.email.password
                },
                tls: {
                    rejectUnauthorized: false
                }
            }
        },
        {
            name: 'Alternative SSL Port 465 (no TLS rejection)',
            config: {
                host: config.email.host,
                port: 465,
                secure: true,
                auth: {
                    user: config.email.user,
                    pass: config.email.password
                },
                tls: {
                    rejectUnauthorized: false,
                    ciphers: 'SSLv3'
                }
            }
        }
    ];

    for (const testConfig of configurations) {
        console.log(`🧪 Testing: ${testConfig.name}`);
        console.log(`   Host: ${testConfig.config.host}:${testConfig.config.port}`);
        console.log(`   Secure: ${testConfig.config.secure}`);
        
        try {
            const transporter = nodemailer.createTransport(testConfig.config);
            await transporter.verify();
            console.log(`✅ SUCCESS: ${testConfig.name} works!\n`);
            
            // Save working configuration
            console.log('💾 Saving working configuration...');
            const workingConfig = `
# Working Email Configuration (Generated by diagnostic)
EMAIL_HOST=${testConfig.config.host}
EMAIL_PORT=${testConfig.config.port}
EMAIL_SECURE=${testConfig.config.secure}
EMAIL_USER=${config.email.user}
EMAIL_PASS=${config.email.password}

# Add this to your .env file to use the working configuration
`;
            
            require('fs').writeFileSync('working-email-config.txt', workingConfig);
            console.log('✅ Working configuration saved to: working-email-config.txt');
            console.log('\n🎉 Found working email configuration!');
            console.log(`✅ Use: Host=${testConfig.config.host}, Port=${testConfig.config.port}, Secure=${testConfig.config.secure}`);
            
            return testConfig.config;
            
        } catch (error) {
            console.log(`❌ FAILED: ${error.message}`);
            console.log('');
        }
    }

    console.log('😞 None of the standard configurations worked.');
    console.log('\n🔧 Additional troubleshooting suggestions:');
    console.log('1. Contact your email provider (acesmitadt.com) for exact SMTP settings');
    console.log('2. Check if your network/firewall blocks SMTP ports');
    console.log('3. Verify if the email server requires app-specific passwords');
    console.log('4. Try using a different email provider temporarily (Gmail, Outlook)');
    
    return null;
}

async function testWithGmail() {
    console.log('\n🔄 Would you like to test with Gmail as an alternative?');
    console.log('You can create a Gmail app password and test with Gmail SMTP:');
    console.log('Host: smtp.gmail.com, Port: 587, Secure: false (STARTTLS)');
}

// Run the diagnostic
if (require.main === module) {
    testMultipleConfigurations().then((workingConfig) => {
        if (!workingConfig) {
            testWithGmail();
        }
    });
}

module.exports = { testMultipleConfigurations };