// test-email.js - Test script to verify email configuration
const nodemailer = require('nodemailer');
const config = require('./config');

async function testEmailConfiguration() {
    console.log('🧪 Testing Email Configuration');
    console.log('==============================\n');

    console.log('📧 Email Settings:');
    console.log(`   Host: ${config.email.host}`);
    console.log(`   Port: ${config.email.port}`);
    console.log(`   Secure: ${config.email.secure}`);
    console.log(`   User: ${config.email.user}`);
    console.log(`   Password: ${config.email.password ? '***' : 'NOT SET'}\n`);

    if (!config.email.password) {
        console.error('❌ Email password not set in .env file!');
        console.log('💡 Please add EMAIL_PASS=your_password to .env file');
        process.exit(1);
    }

    try {
        // Create transporter
        const transporter = nodemailer.createTransport({
            host: config.email.host,
            port: config.email.port,
            secure: config.email.secure,
            auth: {
                user: config.email.user,
                pass: config.email.password
            },
            tls: {
                rejectUnauthorized: false
            }
        });

        console.log('🔄 Verifying SMTP connection...');
        await transporter.verify();
        console.log('✅ SMTP connection verified successfully!\n');

        // Send test email
        console.log('📤 Sending test email...');
        const testMailOptions = {
            from: `"${config.sender.name}" <${config.sender.email}>`,
            to: config.email.user, // Send to self
            subject: `🧪 Test Email - ${config.event.name} Ticket System`,
            html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                    <h2 style="color: #2c3e50;">✅ Email Configuration Test Successful!</h2>
                    <p>This is a test email to verify that your email configuration is working correctly for the <strong>${config.event.name}</strong> ticket sending system.</p>
                    
                    <div style="background: #f8f9fa; padding: 20px; border-radius: 10px; margin: 20px 0;">
                        <h3 style="color: #27ae60; margin-top: 0;">📊 Configuration Details:</h3>
                        <ul>
                            <li><strong>SMTP Host:</strong> ${config.email.host}</li>
                            <li><strong>Port:</strong> ${config.email.port}</li>
                            <li><strong>Security:</strong> ${config.email.secure ? 'SSL/TLS' : 'None'}</li>
                            <li><strong>From Email:</strong> ${config.sender.email}</li>
                        </ul>
                    </div>
                    
                    <div style="background: #e8f5e8; padding: 20px; border-radius: 10px; border-left: 5px solid #27ae60;">
                        <p><strong>✅ Your email system is ready to send tickets!</strong></p>
                        <p>You can now run <code>npm start</code> to begin sending tickets to all attendees.</p>
                    </div>
                    
                    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
                    <p style="color: #7f8c8d; font-size: 0.9em;">
                        This test email was sent on ${new Date().toLocaleString()}<br>
                        Generated by ${config.event.organizer} Ticket System
                    </p>
                </div>
            `
        };

        const result = await transporter.sendMail(testMailOptions);
        console.log('✅ Test email sent successfully!');
        console.log(`📧 Message ID: ${result.messageId}`);
        console.log('📬 Check your inbox for the test email.\n');

        console.log('🎉 Email configuration is working perfectly!');
        console.log('💡 You can now run "npm start" to send tickets to all attendees.');

    } catch (error) {
        console.error('❌ Email configuration test failed!');
        console.error(`Error: ${error.message}\n`);

        console.log('🔧 Troubleshooting Tips:');
        console.log('1. Verify your email password in the .env file');
        console.log('2. Check if your email provider allows SMTP access');
        console.log('3. Ensure your firewall allows connections to port 465');
        console.log('4. Try using an app-specific password if you have 2FA enabled');
        console.log('5. Contact your email provider for SMTP configuration details');

        process.exit(1);
    }
}

// Run the test
if (require.main === module) {
    testEmailConfiguration();
}

module.exports = { testEmailConfiguration };